name: AppSweep mobile application security testing
on: [pull_request_target]
jobs:
  upload-app-to-appsweep:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Upload app to appSweep with Gradle
        env:
          APPSWEEP_API_KEY: ${{secrets.gs_appsweep_6zFDQ96_d4ilOBNzYPjWxboDOTH41qtT9BWZ4esY}}
          run: ./gradlew uploadToAppSweepRelease